// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Auth struct {
	BaseRepresentation
	// The certificate property
	certificate *string
	// The method property
	method *string
	// The secret property
	secret *string
}

// NewAuth instantiates a new Auth and sets the default values.
func NewAuth() *Auth {
	m := &Auth{
		BaseRepresentation: *NewBaseRepresentation(),
	}
	return m
}

// CreateAuthFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuthFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAuth(), nil
}

// GetCertificate gets the certificate property value. The certificate property
// returns a *string when successful
func (m *Auth) GetCertificate() *string {
	return m.certificate
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Auth) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.BaseRepresentation.GetFieldDeserializers()
	res["certificate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCertificate(val)
		}
		return nil
	}
	res["method"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMethod(val)
		}
		return nil
	}
	res["secret"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSecret(val)
		}
		return nil
	}
	return res
}

// GetMethod gets the method property value. The method property
// returns a *string when successful
func (m *Auth) GetMethod() *string {
	return m.method
}

// GetSecret gets the secret property value. The secret property
// returns a *string when successful
func (m *Auth) GetSecret() *string {
	return m.secret
}

// Serialize serializes information the current object
func (m *Auth) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.BaseRepresentation.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteStringValue("certificate", m.GetCertificate())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("method", m.GetMethod())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("secret", m.GetSecret())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetCertificate sets the certificate property value. The certificate property
func (m *Auth) SetCertificate(value *string) {
	m.certificate = value
}

// SetMethod sets the method property value. The method property
func (m *Auth) SetMethod(value *string) {
	m.method = value
}

// SetSecret sets the secret property value. The secret property
func (m *Auth) SetSecret(value *string) {
	m.secret = value
}

type Authable interface {
	BaseRepresentationable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCertificate() *string
	GetMethod() *string
	GetSecret() *string
	SetCertificate(value *string)
	SetMethod(value *string)
	SetSecret(value *string)
}
