// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BaseClientRepresentation struct {
    BaseRepresentation
    // The appUrl property
    appUrl *string
    // The clientId property
    clientId *string
    // The description property
    description *string
    // The displayName property
    displayName *string
    // The enabled property
    enabled *bool
    // The protocol property
    protocol *string
    // The redirectUris property
    redirectUris []string
    // The roles property
    roles []string
}
// NewBaseClientRepresentation instantiates a new BaseClientRepresentation and sets the default values.
func NewBaseClientRepresentation()(*BaseClientRepresentation) {
    m := &BaseClientRepresentation{
        BaseRepresentation: *NewBaseRepresentation(),
    }
    return m
}
// CreateBaseClientRepresentationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBaseClientRepresentationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBaseClientRepresentation(), nil
}
// GetAppUrl gets the appUrl property value. The appUrl property
// returns a *string when successful
func (m *BaseClientRepresentation) GetAppUrl()(*string) {
    return m.appUrl
}
// GetClientId gets the clientId property value. The clientId property
// returns a *string when successful
func (m *BaseClientRepresentation) GetClientId()(*string) {
    return m.clientId
}
// GetDescription gets the description property value. The description property
// returns a *string when successful
func (m *BaseClientRepresentation) GetDescription()(*string) {
    return m.description
}
// GetDisplayName gets the displayName property value. The displayName property
// returns a *string when successful
func (m *BaseClientRepresentation) GetDisplayName()(*string) {
    return m.displayName
}
// GetEnabled gets the enabled property value. The enabled property
// returns a *bool when successful
func (m *BaseClientRepresentation) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BaseClientRepresentation) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := m.BaseRepresentation.GetFieldDeserializers()
    res["appUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAppUrl(val)
        }
        return nil
    }
    res["clientId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetClientId(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["displayName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDisplayName(val)
        }
        return nil
    }
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    res["protocol"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProtocol(val)
        }
        return nil
    }
    res["redirectUris"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetRedirectUris(res)
        }
        return nil
    }
    res["roles"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetRoles(res)
        }
        return nil
    }
    return res
}
// GetProtocol gets the protocol property value. The protocol property
// returns a *string when successful
func (m *BaseClientRepresentation) GetProtocol()(*string) {
    return m.protocol
}
// GetRedirectUris gets the redirectUris property value. The redirectUris property
// returns a []string when successful
func (m *BaseClientRepresentation) GetRedirectUris()([]string) {
    return m.redirectUris
}
// GetRoles gets the roles property value. The roles property
// returns a []string when successful
func (m *BaseClientRepresentation) GetRoles()([]string) {
    return m.roles
}
// Serialize serializes information the current object
func (m *BaseClientRepresentation) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    err := m.BaseRepresentation.Serialize(writer)
    if err != nil {
        return err
    }
    {
        err = writer.WriteStringValue("appUrl", m.GetAppUrl())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("clientId", m.GetClientId())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("displayName", m.GetDisplayName())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    {
        err = writer.WriteStringValue("protocol", m.GetProtocol())
        if err != nil {
            return err
        }
    }
    if m.GetRedirectUris() != nil {
        err = writer.WriteCollectionOfStringValues("redirectUris", m.GetRedirectUris())
        if err != nil {
            return err
        }
    }
    if m.GetRoles() != nil {
        err = writer.WriteCollectionOfStringValues("roles", m.GetRoles())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAppUrl sets the appUrl property value. The appUrl property
func (m *BaseClientRepresentation) SetAppUrl(value *string)() {
    m.appUrl = value
}
// SetClientId sets the clientId property value. The clientId property
func (m *BaseClientRepresentation) SetClientId(value *string)() {
    m.clientId = value
}
// SetDescription sets the description property value. The description property
func (m *BaseClientRepresentation) SetDescription(value *string)() {
    m.description = value
}
// SetDisplayName sets the displayName property value. The displayName property
func (m *BaseClientRepresentation) SetDisplayName(value *string)() {
    m.displayName = value
}
// SetEnabled sets the enabled property value. The enabled property
func (m *BaseClientRepresentation) SetEnabled(value *bool)() {
    m.enabled = value
}
// SetProtocol sets the protocol property value. The protocol property
func (m *BaseClientRepresentation) SetProtocol(value *string)() {
    m.protocol = value
}
// SetRedirectUris sets the redirectUris property value. The redirectUris property
func (m *BaseClientRepresentation) SetRedirectUris(value []string)() {
    m.redirectUris = value
}
// SetRoles sets the roles property value. The roles property
func (m *BaseClientRepresentation) SetRoles(value []string)() {
    m.roles = value
}
type BaseClientRepresentationable interface {
    BaseRepresentationable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAppUrl()(*string)
    GetClientId()(*string)
    GetDescription()(*string)
    GetDisplayName()(*string)
    GetEnabled()(*bool)
    GetProtocol()(*string)
    GetRedirectUris()([]string)
    GetRoles()([]string)
    SetAppUrl(value *string)()
    SetClientId(value *string)()
    SetDescription(value *string)()
    SetDisplayName(value *string)()
    SetEnabled(value *bool)()
    SetProtocol(value *string)()
    SetRedirectUris(value []string)()
    SetRoles(value []string)()
}
