// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Flow int

const (
    STANDARD_FLOW Flow = iota
    IMPLICIT_FLOW
    DIRECT_GRANT_FLOW
    SERVICE_ACCOUNT_FLOW
    TOKEN_EXCHANGE_FLOW
    DEVICE_FLOW
    CIBA_FLOW
)

func (i Flow) String() string {
    return []string{"STANDARD", "IMPLICIT", "DIRECT_GRANT", "SERVICE_ACCOUNT", "TOKEN_EXCHANGE", "DEVICE", "CIBA"}[i]
}
func ParseFlow(v string) (any, error) {
    result := STANDARD_FLOW
    switch v {
        case "STANDARD":
            result = STANDARD_FLOW
        case "IMPLICIT":
            result = IMPLICIT_FLOW
        case "DIRECT_GRANT":
            result = DIRECT_GRANT_FLOW
        case "SERVICE_ACCOUNT":
            result = SERVICE_ACCOUNT_FLOW
        case "TOKEN_EXCHANGE":
            result = TOKEN_EXCHANGE_FLOW
        case "DEVICE":
            result = DEVICE_FLOW
        case "CIBA":
            result = CIBA_FLOW
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeFlow(values []Flow) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Flow) isMultiValue() bool {
    return false
}
