// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OIDCClientRepresentation struct {
	BaseClientRepresentation
	// The auth property
	auth Authable
	// The loginFlows property
	loginFlows []Flow
	// The serviceAccountRoles property
	serviceAccountRoles []string
	// The webOrigins property
	webOrigins []string
}

// NewOIDCClientRepresentation instantiates a new OIDCClientRepresentation and sets the default values.
func NewOIDCClientRepresentation() *OIDCClientRepresentation {
	m := &OIDCClientRepresentation{
		BaseClientRepresentation: *NewBaseClientRepresentation(),
	}
	return m
}

// CreateOIDCClientRepresentationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOIDCClientRepresentationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewOIDCClientRepresentation(), nil
}

// GetAuth gets the auth property value. The auth property
// returns a Authable when successful
func (m *OIDCClientRepresentation) GetAuth() Authable {
	return m.auth
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OIDCClientRepresentation) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.BaseClientRepresentation.GetFieldDeserializers()
	res["auth"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateAuthFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAuth(val.(Authable))
		}
		return nil
	}
	res["loginFlows"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfEnumValues(ParseFlow)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]Flow, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*Flow))
				}
			}
			m.SetLoginFlows(res)
		}
		return nil
	}
	res["serviceAccountRoles"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*string))
				}
			}
			m.SetServiceAccountRoles(res)
		}
		return nil
	}
	res["webOrigins"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *(v.(*string))
				}
			}
			m.SetWebOrigins(res)
		}
		return nil
	}
	return res
}

// GetLoginFlows gets the loginFlows property value. The loginFlows property
// returns a []Flow when successful
func (m *OIDCClientRepresentation) GetLoginFlows() []Flow {
	return m.loginFlows
}

// GetServiceAccountRoles gets the serviceAccountRoles property value. The serviceAccountRoles property
// returns a []string when successful
func (m *OIDCClientRepresentation) GetServiceAccountRoles() []string {
	return m.serviceAccountRoles
}

// GetWebOrigins gets the webOrigins property value. The webOrigins property
// returns a []string when successful
func (m *OIDCClientRepresentation) GetWebOrigins() []string {
	return m.webOrigins
}

// Serialize serializes information the current object
func (m *OIDCClientRepresentation) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.BaseClientRepresentation.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteObjectValue("auth", m.GetAuth())
		if err != nil {
			return err
		}
	}
	if m.GetLoginFlows() != nil {
		err = writer.WriteCollectionOfStringValues("loginFlows", SerializeFlow(m.GetLoginFlows()))
		if err != nil {
			return err
		}
	}
	if m.GetServiceAccountRoles() != nil {
		err = writer.WriteCollectionOfStringValues("serviceAccountRoles", m.GetServiceAccountRoles())
		if err != nil {
			return err
		}
	}
	if m.GetWebOrigins() != nil {
		err = writer.WriteCollectionOfStringValues("webOrigins", m.GetWebOrigins())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAuth sets the auth property value. The auth property
func (m *OIDCClientRepresentation) SetAuth(value Authable) {
	m.auth = value
}

// SetLoginFlows sets the loginFlows property value. The loginFlows property
func (m *OIDCClientRepresentation) SetLoginFlows(value []Flow) {
	m.loginFlows = value
}

// SetServiceAccountRoles sets the serviceAccountRoles property value. The serviceAccountRoles property
func (m *OIDCClientRepresentation) SetServiceAccountRoles(value []string) {
	m.serviceAccountRoles = value
}

// SetWebOrigins sets the webOrigins property value. The webOrigins property
func (m *OIDCClientRepresentation) SetWebOrigins(value []string) {
	m.webOrigins = value
}

type OIDCClientRepresentationable interface {
	BaseClientRepresentationable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAuth() Authable
	GetLoginFlows() []Flow
	GetServiceAccountRoles() []string
	GetWebOrigins() []string
	SetAuth(value Authable)
	SetLoginFlows(value []Flow)
	SetServiceAccountRoles(value []string)
	SetWebOrigins(value []string)
}
