// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// SAMLClientRepresentation sAML Client configuration
type SAMLClientRepresentation struct {
	BaseClientRepresentation
	// The allowEcpFlow property
	allowEcpFlow *bool
	// The clientSignatureRequired property
	clientSignatureRequired *bool
	// The forceNameIdFormat property
	forceNameIdFormat *bool
	// The forcePostBinding property
	forcePostBinding *bool
	// The frontChannelLogout property
	frontChannelLogout *bool
	// The includeAuthnStatement property
	includeAuthnStatement *bool
	// The nameIdFormat property
	nameIdFormat *string
	// The signAssertions property
	signAssertions *bool
	// The signatureAlgorithm property
	signatureAlgorithm *string
	// The signatureCanonicalizationMethod property
	signatureCanonicalizationMethod *string
	// The signDocuments property
	signDocuments *bool
	// The signingCertificate property
	signingCertificate *string
}

// NewSAMLClientRepresentation instantiates a new SAMLClientRepresentation and sets the default values.
func NewSAMLClientRepresentation() *SAMLClientRepresentation {
	m := &SAMLClientRepresentation{
		BaseClientRepresentation: *NewBaseClientRepresentation(),
	}
	return m
}

// CreateSAMLClientRepresentationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSAMLClientRepresentationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewSAMLClientRepresentation(), nil
}

// GetAllowEcpFlow gets the allowEcpFlow property value. The allowEcpFlow property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetAllowEcpFlow() *bool {
	return m.allowEcpFlow
}

// GetClientSignatureRequired gets the clientSignatureRequired property value. The clientSignatureRequired property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetClientSignatureRequired() *bool {
	return m.clientSignatureRequired
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SAMLClientRepresentation) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.BaseClientRepresentation.GetFieldDeserializers()
	res["allowEcpFlow"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAllowEcpFlow(val)
		}
		return nil
	}
	res["clientSignatureRequired"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClientSignatureRequired(val)
		}
		return nil
	}
	res["forceNameIdFormat"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetForceNameIdFormat(val)
		}
		return nil
	}
	res["forcePostBinding"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetForcePostBinding(val)
		}
		return nil
	}
	res["frontChannelLogout"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFrontChannelLogout(val)
		}
		return nil
	}
	res["includeAuthnStatement"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIncludeAuthnStatement(val)
		}
		return nil
	}
	res["nameIdFormat"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNameIdFormat(val)
		}
		return nil
	}
	res["signAssertions"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSignAssertions(val)
		}
		return nil
	}
	res["signatureAlgorithm"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSignatureAlgorithm(val)
		}
		return nil
	}
	res["signatureCanonicalizationMethod"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSignatureCanonicalizationMethod(val)
		}
		return nil
	}
	res["signDocuments"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSignDocuments(val)
		}
		return nil
	}
	res["signingCertificate"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSigningCertificate(val)
		}
		return nil
	}
	return res
}

// GetForceNameIdFormat gets the forceNameIdFormat property value. The forceNameIdFormat property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetForceNameIdFormat() *bool {
	return m.forceNameIdFormat
}

// GetForcePostBinding gets the forcePostBinding property value. The forcePostBinding property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetForcePostBinding() *bool {
	return m.forcePostBinding
}

// GetFrontChannelLogout gets the frontChannelLogout property value. The frontChannelLogout property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetFrontChannelLogout() *bool {
	return m.frontChannelLogout
}

// GetIncludeAuthnStatement gets the includeAuthnStatement property value. The includeAuthnStatement property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetIncludeAuthnStatement() *bool {
	return m.includeAuthnStatement
}

// GetNameIdFormat gets the nameIdFormat property value. The nameIdFormat property
// returns a *string when successful
func (m *SAMLClientRepresentation) GetNameIdFormat() *string {
	return m.nameIdFormat
}

// GetSignAssertions gets the signAssertions property value. The signAssertions property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetSignAssertions() *bool {
	return m.signAssertions
}

// GetSignatureAlgorithm gets the signatureAlgorithm property value. The signatureAlgorithm property
// returns a *string when successful
func (m *SAMLClientRepresentation) GetSignatureAlgorithm() *string {
	return m.signatureAlgorithm
}

// GetSignatureCanonicalizationMethod gets the signatureCanonicalizationMethod property value. The signatureCanonicalizationMethod property
// returns a *string when successful
func (m *SAMLClientRepresentation) GetSignatureCanonicalizationMethod() *string {
	return m.signatureCanonicalizationMethod
}

// GetSignDocuments gets the signDocuments property value. The signDocuments property
// returns a *bool when successful
func (m *SAMLClientRepresentation) GetSignDocuments() *bool {
	return m.signDocuments
}

// GetSigningCertificate gets the signingCertificate property value. The signingCertificate property
// returns a *string when successful
func (m *SAMLClientRepresentation) GetSigningCertificate() *string {
	return m.signingCertificate
}

// Serialize serializes information the current object
func (m *SAMLClientRepresentation) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.BaseClientRepresentation.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteBoolValue("allowEcpFlow", m.GetAllowEcpFlow())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("clientSignatureRequired", m.GetClientSignatureRequired())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("forceNameIdFormat", m.GetForceNameIdFormat())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("forcePostBinding", m.GetForcePostBinding())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("frontChannelLogout", m.GetFrontChannelLogout())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("includeAuthnStatement", m.GetIncludeAuthnStatement())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("nameIdFormat", m.GetNameIdFormat())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("signAssertions", m.GetSignAssertions())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("signatureAlgorithm", m.GetSignatureAlgorithm())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("signatureCanonicalizationMethod", m.GetSignatureCanonicalizationMethod())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteBoolValue("signDocuments", m.GetSignDocuments())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("signingCertificate", m.GetSigningCertificate())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAllowEcpFlow sets the allowEcpFlow property value. The allowEcpFlow property
func (m *SAMLClientRepresentation) SetAllowEcpFlow(value *bool) {
	m.allowEcpFlow = value
}

// SetClientSignatureRequired sets the clientSignatureRequired property value. The clientSignatureRequired property
func (m *SAMLClientRepresentation) SetClientSignatureRequired(value *bool) {
	m.clientSignatureRequired = value
}

// SetForceNameIdFormat sets the forceNameIdFormat property value. The forceNameIdFormat property
func (m *SAMLClientRepresentation) SetForceNameIdFormat(value *bool) {
	m.forceNameIdFormat = value
}

// SetForcePostBinding sets the forcePostBinding property value. The forcePostBinding property
func (m *SAMLClientRepresentation) SetForcePostBinding(value *bool) {
	m.forcePostBinding = value
}

// SetFrontChannelLogout sets the frontChannelLogout property value. The frontChannelLogout property
func (m *SAMLClientRepresentation) SetFrontChannelLogout(value *bool) {
	m.frontChannelLogout = value
}

// SetIncludeAuthnStatement sets the includeAuthnStatement property value. The includeAuthnStatement property
func (m *SAMLClientRepresentation) SetIncludeAuthnStatement(value *bool) {
	m.includeAuthnStatement = value
}

// SetNameIdFormat sets the nameIdFormat property value. The nameIdFormat property
func (m *SAMLClientRepresentation) SetNameIdFormat(value *string) {
	m.nameIdFormat = value
}

// SetSignAssertions sets the signAssertions property value. The signAssertions property
func (m *SAMLClientRepresentation) SetSignAssertions(value *bool) {
	m.signAssertions = value
}

// SetSignatureAlgorithm sets the signatureAlgorithm property value. The signatureAlgorithm property
func (m *SAMLClientRepresentation) SetSignatureAlgorithm(value *string) {
	m.signatureAlgorithm = value
}

// SetSignatureCanonicalizationMethod sets the signatureCanonicalizationMethod property value. The signatureCanonicalizationMethod property
func (m *SAMLClientRepresentation) SetSignatureCanonicalizationMethod(value *string) {
	m.signatureCanonicalizationMethod = value
}

// SetSignDocuments sets the signDocuments property value. The signDocuments property
func (m *SAMLClientRepresentation) SetSignDocuments(value *bool) {
	m.signDocuments = value
}

// SetSigningCertificate sets the signingCertificate property value. The signingCertificate property
func (m *SAMLClientRepresentation) SetSigningCertificate(value *string) {
	m.signingCertificate = value
}

type SAMLClientRepresentationable interface {
	BaseClientRepresentationable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAllowEcpFlow() *bool
	GetClientSignatureRequired() *bool
	GetForceNameIdFormat() *bool
	GetForcePostBinding() *bool
	GetFrontChannelLogout() *bool
	GetIncludeAuthnStatement() *bool
	GetNameIdFormat() *string
	GetSignAssertions() *bool
	GetSignatureAlgorithm() *string
	GetSignatureCanonicalizationMethod() *string
	GetSignDocuments() *bool
	GetSigningCertificate() *string
	SetAllowEcpFlow(value *bool)
	SetClientSignatureRequired(value *bool)
	SetForceNameIdFormat(value *bool)
	SetForcePostBinding(value *bool)
	SetFrontChannelLogout(value *bool)
	SetIncludeAuthnStatement(value *bool)
	SetNameIdFormat(value *string)
	SetSignAssertions(value *bool)
	SetSignatureAlgorithm(value *string)
	SetSignatureCanonicalizationMethod(value *string)
	SetSignDocuments(value *bool)
	SetSigningCertificate(value *string)
}
