// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package admin

import (
	"context"
	i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205 "github.com/keycloak/terraform-provider-keycloak/internal/keycloak/adminv2/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
	ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6 "strings"
)

// ApiItemClientsWithVersionItemRequestBuilder builds and executes requests for operations under \admin\api\{realmName}\clients\{version}
type ApiItemClientsWithVersionItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// WithVersion composed type wrapper for classes i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable, i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
type WithVersion struct {
	// Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
	oIDCClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
	// Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
	sAMLClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
}

// NewWithVersion instantiates a new WithVersion and sets the default values.
func NewWithVersion() *WithVersion {
	m := &WithVersion{}
	return m
}

// CreateWithVersionFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateWithVersionFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	result := NewWithVersion()
	if parseNode != nil {
		mappingValueNode, err := parseNode.GetChildNode("protocol")
		if err != nil {
			return nil, err
		}
		if mappingValueNode != nil {
			mappingValue, err := mappingValueNode.GetStringValue()
			if err != nil {
				return nil, err
			}
			if mappingValue != nil {
				if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "openid-connect") {
					result.SetOIDCClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewOIDCClientRepresentation())
				} else if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "saml") {
					result.SetSAMLClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewSAMLClientRepresentation())
				}
			}
		}
	}
	return result, nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *WithVersion) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	if m.GetOIDCClientRepresentation() != nil {
		return m.GetOIDCClientRepresentation().GetFieldDeserializers()
	} else if m.GetSAMLClientRepresentation() != nil {
		return m.GetSAMLClientRepresentation().GetFieldDeserializers()
	}
	return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
}

// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *WithVersion) GetIsComposedType() bool {
	return true
}

// GetOIDCClientRepresentation gets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
// returns a OIDCClientRepresentationable when successful
func (m *WithVersion) GetOIDCClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable {
	return m.oIDCClientRepresentation
}

// GetSAMLClientRepresentation gets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
// returns a SAMLClientRepresentationable when successful
func (m *WithVersion) GetSAMLClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable {
	return m.sAMLClientRepresentation
}

// Serialize serializes information the current object
func (m *WithVersion) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetOIDCClientRepresentation() != nil {
		err := writer.WriteObjectValue("", m.GetOIDCClientRepresentation())
		if err != nil {
			return err
		}
	} else if m.GetSAMLClientRepresentation() != nil {
		err := writer.WriteObjectValue("", m.GetSAMLClientRepresentation())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetOIDCClientRepresentation sets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
func (m *WithVersion) SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable) {
	m.oIDCClientRepresentation = value
}

// SetSAMLClientRepresentation sets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
func (m *WithVersion) SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable) {
	m.sAMLClientRepresentation = value
}

// WithVersionPostRequestBody composed type wrapper for classes i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable, i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
type WithVersionPostRequestBody struct {
	// Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
	oIDCClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
	// Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
	sAMLClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
}

// NewWithVersionPostRequestBody instantiates a new WithVersionPostRequestBody and sets the default values.
func NewWithVersionPostRequestBody() *WithVersionPostRequestBody {
	m := &WithVersionPostRequestBody{}
	return m
}

// CreateWithVersionPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateWithVersionPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	result := NewWithVersionPostRequestBody()
	if parseNode != nil {
		mappingValueNode, err := parseNode.GetChildNode("protocol")
		if err != nil {
			return nil, err
		}
		if mappingValueNode != nil {
			mappingValue, err := mappingValueNode.GetStringValue()
			if err != nil {
				return nil, err
			}
			if mappingValue != nil {
				if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "openid-connect") {
					result.SetOIDCClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewOIDCClientRepresentation())
				} else if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "saml") {
					result.SetSAMLClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewSAMLClientRepresentation())
				}
			}
		}
	}
	return result, nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *WithVersionPostRequestBody) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	if m.GetOIDCClientRepresentation() != nil {
		return m.GetOIDCClientRepresentation().GetFieldDeserializers()
	} else if m.GetSAMLClientRepresentation() != nil {
		return m.GetSAMLClientRepresentation().GetFieldDeserializers()
	}
	return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
}

// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *WithVersionPostRequestBody) GetIsComposedType() bool {
	return true
}

// GetOIDCClientRepresentation gets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
// returns a OIDCClientRepresentationable when successful
func (m *WithVersionPostRequestBody) GetOIDCClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable {
	return m.oIDCClientRepresentation
}

// GetSAMLClientRepresentation gets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
// returns a SAMLClientRepresentationable when successful
func (m *WithVersionPostRequestBody) GetSAMLClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable {
	return m.sAMLClientRepresentation
}

// Serialize serializes information the current object
func (m *WithVersionPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetOIDCClientRepresentation() != nil {
		err := writer.WriteObjectValue("", m.GetOIDCClientRepresentation())
		if err != nil {
			return err
		}
	} else if m.GetSAMLClientRepresentation() != nil {
		err := writer.WriteObjectValue("", m.GetSAMLClientRepresentation())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetOIDCClientRepresentation sets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
func (m *WithVersionPostRequestBody) SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable) {
	m.oIDCClientRepresentation = value
}

// SetSAMLClientRepresentation sets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
func (m *WithVersionPostRequestBody) SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable) {
	m.sAMLClientRepresentation = value
}

type WithVersionable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetOIDCClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
	GetSAMLClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
	SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)
	SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)
}
type WithVersionPostRequestBodyable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetOIDCClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
	GetSAMLClientRepresentation() i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
	SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)
	SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)
}

// ById gets an item from the github.com/keycloak/terraform-provider-keycloak/internal/keycloak/adminv2.admin.api.item.clients.item.item collection
// returns a *ApiItemClientsItemVersionItemRequestBuilder when successful
func (m *ApiItemClientsWithVersionItemRequestBuilder) ById(id string) *ApiItemClientsItemVersionItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewApiItemClientsItemVersionItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewApiItemClientsWithVersionItemRequestBuilderInternal instantiates a new ApiItemClientsWithVersionItemRequestBuilder and sets the default values.
func NewApiItemClientsWithVersionItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ApiItemClientsWithVersionItemRequestBuilder {
	m := &ApiItemClientsWithVersionItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/admin/api/{realmName}/clients/{version}", pathParameters),
	}
	return m
}

// NewApiItemClientsWithVersionItemRequestBuilder instantiates a new ApiItemClientsWithVersionItemRequestBuilder and sets the default values.
func NewApiItemClientsWithVersionItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ApiItemClientsWithVersionItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewApiItemClientsWithVersionItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Get returns a list of all clients in the realm
// returns a []WithVersionable when successful
func (m *ApiItemClientsWithVersionItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) ([]WithVersionable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, CreateWithVersionFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	val := make([]WithVersionable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(WithVersionable)
		}
	}
	return val, nil
}

// Post creates a new client in the realm
// returns a UntypedNodeable when successful
func (m *ApiItemClientsWithVersionItemRequestBuilder) Post(ctx context.Context, body WithVersionPostRequestBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}

// ToGetRequestInformation returns a list of all clients in the realm
// returns a *RequestInformation when successful
func (m *ApiItemClientsWithVersionItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPostRequestInformation creates a new client in the realm
// returns a *RequestInformation when successful
func (m *ApiItemClientsWithVersionItemRequestBuilder) ToPostRequestInformation(ctx context.Context, body WithVersionPostRequestBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ApiItemClientsWithVersionItemRequestBuilder when successful
func (m *ApiItemClientsWithVersionItemRequestBuilder) WithUrl(rawUrl string) *ApiItemClientsWithVersionItemRequestBuilder {
	return NewApiItemClientsWithVersionItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
