// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package admin

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ApiItemClientsRequestBuilder builds and executes requests for operations under \admin\api\{realmName}\clients
type ApiItemClientsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByVersion gets an item from the github.com/keycloak/terraform-provider-keycloak/internal/keycloak/adminv2.admin.api.item.clients.item collection
// returns a *ApiItemClientsWithVersionItemRequestBuilder when successful
func (m *ApiItemClientsRequestBuilder) ByVersion(version string)(*ApiItemClientsWithVersionItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if version != "" {
        urlTplParams["version"] = version
    }
    return NewApiItemClientsWithVersionItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewApiItemClientsRequestBuilderInternal instantiates a new ApiItemClientsRequestBuilder and sets the default values.
func NewApiItemClientsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiItemClientsRequestBuilder) {
    m := &ApiItemClientsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/admin/api/{realmName}/clients", pathParameters),
    }
    return m
}
// NewApiItemClientsRequestBuilder instantiates a new ApiItemClientsRequestBuilder and sets the default values.
func NewApiItemClientsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiItemClientsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewApiItemClientsRequestBuilderInternal(urlParams, requestAdapter)
}
