// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package admin

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ApiRequestBuilder builds and executes requests for operations under \admin\api
type ApiRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByRealmName gets an item from the github.com/keycloak/terraform-provider-keycloak/internal/keycloak/adminv2.admin.api.item collection
// returns a *ApiWithRealmNameItemRequestBuilder when successful
func (m *ApiRequestBuilder) ByRealmName(realmName string)(*ApiWithRealmNameItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if realmName != "" {
        urlTplParams["realmName"] = realmName
    }
    return NewApiWithRealmNameItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewApiRequestBuilderInternal instantiates a new ApiRequestBuilder and sets the default values.
func NewApiRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiRequestBuilder) {
    m := &ApiRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/admin/api", pathParameters),
    }
    return m
}
// NewApiRequestBuilder instantiates a new ApiRequestBuilder and sets the default values.
func NewApiRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewApiRequestBuilderInternal(urlParams, requestAdapter)
}
