// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package admin

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ApiWithRealmNameItemRequestBuilder builds and executes requests for operations under \admin\api\{realmName}
type ApiWithRealmNameItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// Clients the clients property
// returns a *ApiItemClientsRequestBuilder when successful
func (m *ApiWithRealmNameItemRequestBuilder) Clients() *ApiItemClientsRequestBuilder {
	return NewApiItemClientsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// NewApiWithRealmNameItemRequestBuilderInternal instantiates a new ApiWithRealmNameItemRequestBuilder and sets the default values.
func NewApiWithRealmNameItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ApiWithRealmNameItemRequestBuilder {
	m := &ApiWithRealmNameItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/admin/api/{realmName}", pathParameters),
	}
	return m
}

// NewApiWithRealmNameItemRequestBuilder instantiates a new ApiWithRealmNameItemRequestBuilder and sets the default values.
func NewApiWithRealmNameItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ApiWithRealmNameItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewApiWithRealmNameItemRequestBuilderInternal(urlParams, requestAdapter)
}
