// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package admin

import (
    "context"
    ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6 "strings"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205 "github.com/keycloak/terraform-provider-keycloak/internal/keycloak/adminv2/models"
)

// ApiItemClientsItemVersionItemRequestBuilder builds and executes requests for operations under \admin\api\{realmName}\clients\{version}\{id}
type ApiItemClientsItemVersionItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// VersionGetResponse composed type wrapper for classes i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable, i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
type VersionGetResponse struct {
    // Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
    oIDCClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
    // Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
    sAMLClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
}
// NewVersionGetResponse instantiates a new VersionGetResponse and sets the default values.
func NewVersionGetResponse()(*VersionGetResponse) {
    m := &VersionGetResponse{
    }
    return m
}
// CreateVersionGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVersionGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewVersionGetResponse()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("protocol")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
                if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "openid-connect") {
                    result.SetOIDCClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewOIDCClientRepresentation())
                } else if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "saml") {
                    result.SetSAMLClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewSAMLClientRepresentation())
                }
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VersionGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetOIDCClientRepresentation() != nil {
        return m.GetOIDCClientRepresentation().GetFieldDeserializers()
    } else if m.GetSAMLClientRepresentation() != nil {
        return m.GetSAMLClientRepresentation().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *VersionGetResponse) GetIsComposedType()(bool) {
    return true
}
// GetOIDCClientRepresentation gets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
// returns a OIDCClientRepresentationable when successful
func (m *VersionGetResponse) GetOIDCClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable) {
    return m.oIDCClientRepresentation
}
// GetSAMLClientRepresentation gets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
// returns a SAMLClientRepresentationable when successful
func (m *VersionGetResponse) GetSAMLClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable) {
    return m.sAMLClientRepresentation
}
// Serialize serializes information the current object
func (m *VersionGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetOIDCClientRepresentation() != nil {
        err := writer.WriteObjectValue("", m.GetOIDCClientRepresentation())
        if err != nil {
            return err
        }
    } else if m.GetSAMLClientRepresentation() != nil {
        err := writer.WriteObjectValue("", m.GetSAMLClientRepresentation())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetOIDCClientRepresentation sets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
func (m *VersionGetResponse) SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)() {
    m.oIDCClientRepresentation = value
}
// SetSAMLClientRepresentation sets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
func (m *VersionGetResponse) SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)() {
    m.sAMLClientRepresentation = value
}
// VersionPatchResponse composed type wrapper for classes i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable, i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
type VersionPatchResponse struct {
    // Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
    oIDCClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
    // Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
    sAMLClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
}
// NewVersionPatchResponse instantiates a new VersionPatchResponse and sets the default values.
func NewVersionPatchResponse()(*VersionPatchResponse) {
    m := &VersionPatchResponse{
    }
    return m
}
// CreateVersionPatchResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVersionPatchResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewVersionPatchResponse()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("protocol")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
                if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "openid-connect") {
                    result.SetOIDCClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewOIDCClientRepresentation())
                } else if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "saml") {
                    result.SetSAMLClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewSAMLClientRepresentation())
                }
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VersionPatchResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetOIDCClientRepresentation() != nil {
        return m.GetOIDCClientRepresentation().GetFieldDeserializers()
    } else if m.GetSAMLClientRepresentation() != nil {
        return m.GetSAMLClientRepresentation().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *VersionPatchResponse) GetIsComposedType()(bool) {
    return true
}
// GetOIDCClientRepresentation gets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
// returns a OIDCClientRepresentationable when successful
func (m *VersionPatchResponse) GetOIDCClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable) {
    return m.oIDCClientRepresentation
}
// GetSAMLClientRepresentation gets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
// returns a SAMLClientRepresentationable when successful
func (m *VersionPatchResponse) GetSAMLClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable) {
    return m.sAMLClientRepresentation
}
// Serialize serializes information the current object
func (m *VersionPatchResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetOIDCClientRepresentation() != nil {
        err := writer.WriteObjectValue("", m.GetOIDCClientRepresentation())
        if err != nil {
            return err
        }
    } else if m.GetSAMLClientRepresentation() != nil {
        err := writer.WriteObjectValue("", m.GetSAMLClientRepresentation())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetOIDCClientRepresentation sets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
func (m *VersionPatchResponse) SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)() {
    m.oIDCClientRepresentation = value
}
// SetSAMLClientRepresentation sets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
func (m *VersionPatchResponse) SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)() {
    m.sAMLClientRepresentation = value
}
// VersionPutRequestBody composed type wrapper for classes i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable, i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
type VersionPutRequestBody struct {
    // Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
    oIDCClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
    // Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
    sAMLClientRepresentation i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
}
// NewVersionPutRequestBody instantiates a new VersionPutRequestBody and sets the default values.
func NewVersionPutRequestBody()(*VersionPutRequestBody) {
    m := &VersionPutRequestBody{
    }
    return m
}
// CreateVersionPutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVersionPutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewVersionPutRequestBody()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("protocol")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
                if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "openid-connect") {
                    result.SetOIDCClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewOIDCClientRepresentation())
                } else if ie967d16dae74a49b5e0e051225c5dac0d76e5e38f13dd1628028cbce108c25b6.EqualFold(*mappingValue, "saml") {
                    result.SetSAMLClientRepresentation(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.NewSAMLClientRepresentation())
                }
            }
        }
    }
    return result, nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VersionPutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetOIDCClientRepresentation() != nil {
        return m.GetOIDCClientRepresentation().GetFieldDeserializers()
    } else if m.GetSAMLClientRepresentation() != nil {
        return m.GetSAMLClientRepresentation().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *VersionPutRequestBody) GetIsComposedType()(bool) {
    return true
}
// GetOIDCClientRepresentation gets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
// returns a OIDCClientRepresentationable when successful
func (m *VersionPutRequestBody) GetOIDCClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable) {
    return m.oIDCClientRepresentation
}
// GetSAMLClientRepresentation gets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
// returns a SAMLClientRepresentationable when successful
func (m *VersionPutRequestBody) GetSAMLClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable) {
    return m.sAMLClientRepresentation
}
// Serialize serializes information the current object
func (m *VersionPutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetOIDCClientRepresentation() != nil {
        err := writer.WriteObjectValue("", m.GetOIDCClientRepresentation())
        if err != nil {
            return err
        }
    } else if m.GetSAMLClientRepresentation() != nil {
        err := writer.WriteObjectValue("", m.GetSAMLClientRepresentation())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetOIDCClientRepresentation sets the OIDCClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable
func (m *VersionPutRequestBody) SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)() {
    m.oIDCClientRepresentation = value
}
// SetSAMLClientRepresentation sets the SAMLClientRepresentation property value. Composed type representation for type i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable
func (m *VersionPutRequestBody) SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)() {
    m.sAMLClientRepresentation = value
}
type VersionGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetOIDCClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)
    GetSAMLClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)
    SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)()
    SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)()
}
type VersionPatchResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetOIDCClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)
    GetSAMLClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)
    SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)()
    SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)()
}
type VersionPutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetOIDCClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)
    GetSAMLClientRepresentation()(i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)
    SetOIDCClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.OIDCClientRepresentationable)()
    SetSAMLClientRepresentation(value i2a8db68df0a4e4d5b692bbda7b62472a1ea7790ae7a25a840bc0146392c10205.SAMLClientRepresentationable)()
}
// NewApiItemClientsItemVersionItemRequestBuilderInternal instantiates a new ApiItemClientsItemVersionItemRequestBuilder and sets the default values.
func NewApiItemClientsItemVersionItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiItemClientsItemVersionItemRequestBuilder) {
    m := &ApiItemClientsItemVersionItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/admin/api/{realmName}/clients/{version}/{id}", pathParameters),
    }
    return m
}
// NewApiItemClientsItemVersionItemRequestBuilder instantiates a new ApiItemClientsItemVersionItemRequestBuilder and sets the default values.
func NewApiItemClientsItemVersionItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ApiItemClientsItemVersionItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewApiItemClientsItemVersionItemRequestBuilderInternal(urlParams, requestAdapter)
}
func (m *ApiItemClientsItemVersionItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, nil)
    if err != nil {
        return err
    }
    return nil
}
// returns a VersionGetResponseable when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(VersionGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateVersionGetResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(VersionGetResponseable), nil
}
// returns a VersionPatchResponseable when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) Patch(ctx context.Context, body []byte, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(VersionPatchResponseable, error) {
    requestInfo, err := m.ToPatchRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateVersionPatchResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(VersionPatchResponseable), nil
}
// returns a UntypedNodeable when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) Put(ctx context.Context, body VersionPutRequestBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, error) {
    requestInfo, err := m.ToPutRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable), nil
}
// returns a *RequestInformation when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    return requestInfo, nil
}
// returns a *RequestInformation when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// returns a *RequestInformation when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) ToPatchRequestInformation(ctx context.Context, body []byte, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PATCH, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetStreamContentAndContentType(body, "application/merge-patch+json")
    return requestInfo, nil
}
// returns a *RequestInformation when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) ToPutRequestInformation(ctx context.Context, body VersionPutRequestBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PUT, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ApiItemClientsItemVersionItemRequestBuilder when successful
func (m *ApiItemClientsItemVersionItemRequestBuilder) WithUrl(rawUrl string)(*ApiItemClientsItemVersionItemRequestBuilder) {
    return NewApiItemClientsItemVersionItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
